name: Push Workflow

on:
  workflow_dispatch:
permissions:
  contents: write
  actions: write
  
jobs:
  push-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Create workflow file
        run: |
          mkdir -p .github/workflows
          echo '
          name: Dummy Workflow
          on: [push]
          jobs:
            test:
              runs-on: ubuntu-latest
              steps:
                - run: echo Hello
          ' > .github/workflows/create.yaml

      - name: Commit and Push with PAT
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote -v
          git add .github/workflows/create.yaml
          git commit -m "Add workflow file"
          git remote set-url origin https://chandramouli-kc:${PAT_TOKEN}@github.com/chandramouli-kc/github-actions.git
          git push origin main
